/** Misyonun ait olduğu ülke: haritadaki adı (world.json) ya da haritada yoksa konumu */
export interface MissionCountry {
  /** Ekranda gösterilen ad */
  label: string;
  /** world.json'daki ülke adı; haritada çizilmeyenler (Vatikan, Kosova, AB) için null */
  mapName: string | null;
  /** Haritada çizilmeyenlerin işaret konumu [boylam, enlem] */
  coord?: [number, number];
}

type Entry = [prefixes: string[], mapName: string | null, coord?: [number, number]];

// Dış kurum kaydında ülke bilgisi yok; misyon adı ülke adıyla başlar
// (ör. "Almanya İstanbul Başkonsolosluğu"). İlk önek ekranda gösterilen addır.
const ENTRIES: Entry[] = [
  [['Afganistan'], 'Afghanistan'],
  [['Almanya'], 'Germany'],
  [['Amerika Birleşik Devletleri', 'ABD'], 'United States'],
  [['Angola'], 'Angola'],
  [['Arjantin'], 'Argentina'],
  [['Arnavutluk'], 'Albania'],
  [['Avrupa Birliği', 'AB'], null, [4.35, 50.85]],
  [['Avustralya'], 'Australia'],
  [['Avusturya'], 'Austria'],
  [['Azerbaycan'], 'Azerbaijan'],
  [['Bahreyn'], 'Bahrain'],
  [['Bangladeş'], 'Bangladesh'],
  [['Belarus', 'Beyaz Rusya'], 'Belarus'],
  [['Belçika'], 'Belgium'],
  [['Benin'], 'Benin'],
  [['Birleşik Arap Emirlikleri', 'BAE'], 'United Arab Emirates'],
  [['Birleşik Krallık', 'İngiltere'], 'United Kingdom'],
  [['Bolivya'], 'Bolivia'],
  [['Bosna-Hersek', 'Bosna Hersek'], 'Bosnia and Herz.'],
  [['Brezilya'], 'Brazil'],
  [['Brunei'], 'Brunei'],
  [['Bulgaristan'], 'Bulgaria'],
  [['Burkina Faso'], 'Burkina Faso'],
  [['Çad'], 'Chad'],
  [['Çek Cumhuriyeti', 'Çekya'], 'Czech Rep.'],
  [['Cezayir'], 'Algeria'],
  [['Cibuti'], 'Djibouti'],
  [['Çin'], 'China'],
  [['Danimarka'], 'Denmark'],
  [['Dominik Cumhuriyeti'], 'Dominican Rep.'],
  [['Ekvador'], 'Ecuador'],
  [['Endonezya'], 'Indonesia'],
  [['Ermenistan'], 'Armenia'],
  [['Estonya'], 'Estonia'],
  [['Etiyopya'], 'Ethiopia'],
  [['Fas'], 'Morocco'],
  [['Fildişi Sahili'], "Côte d'Ivoire"],
  [['Filipinler'], 'Philippines'],
  [['Filistin'], 'Palestine'],
  [['Finlandiya'], 'Finland'],
  [['Fransa'], 'France'],
  [['Gabon'], 'Gabon'],
  [['Gambiya'], 'Gambia'],
  [['Gana'], 'Ghana'],
  [['Gine'], 'Guinea'],
  [['Guatemala'], 'Guatemala'],
  [['Güney Afrika'], 'South Africa'],
  [['Güney Kore', 'Kore'], 'Korea'],
  [['Güney Sudan'], 'S. Sudan'],
  [['Gürcistan'], 'Georgia'],
  [['Hindistan'], 'India'],
  [['Hırvatistan'], 'Croatia'],
  [['Hollanda'], 'Netherlands'],
  [['Irak'], 'Iraq'],
  [['İran'], 'Iran'],
  [['İrlanda'], 'Ireland'],
  [['İspanya'], 'Spain'],
  [['İsrail'], 'Israel'],
  [['İsveç'], 'Sweden'],
  [['İsviçre'], 'Switzerland'],
  [['İtalya'], 'Italy'],
  [['İzlanda'], 'Iceland'],
  [['Jamaika'], 'Jamaica'],
  [['Japonya'], 'Japan'],
  [['Kamboçya'], 'Cambodia'],
  [['Kamerun'], 'Cameroon'],
  [['Kanada'], 'Canada'],
  [['Karadağ'], 'Montenegro'],
  [['Katar'], 'Qatar'],
  [['Kazakistan'], 'Kazakhstan'],
  [['Kenya'], 'Kenya'],
  [['Kırgızistan'], 'Kyrgyzstan'],
  [['Kolombiya'], 'Colombia'],
  [['Kongo Demokratik Cumhuriyeti'], 'Dem. Rep. Congo'],
  [['Kongo'], 'Congo'],
  [['Kosova'], null, [20.9, 42.6]],
  [['Kosta Rika'], 'Costa Rica'],
  [['Küba'], 'Cuba'],
  [['Kuveyt'], 'Kuwait'],
  [['Kuzey Kıbrıs Türk Cumhuriyeti', 'KKTC'], 'N. Cyprus'],
  [['Kuzey Kore'], 'Dem. Rep. Korea'],
  [['Kuzey Makedonya', 'Makedonya'], 'Macedonia'],
  [['Laos'], 'Lao PDR'],
  [['Letonya'], 'Latvia'],
  [['Libya'], 'Libya'],
  [['Litvanya'], 'Lithuania'],
  [['Lübnan'], 'Lebanon'],
  [['Lüksemburg'], 'Luxembourg'],
  [['Macaristan'], 'Hungary'],
  [['Madagaskar'], 'Madagascar'],
  [['Malezya'], 'Malaysia'],
  [['Mali'], 'Mali'],
  [['Malta'], 'Malta'],
  [['Meksika'], 'Mexico'],
  [['Mısır'], 'Egypt'],
  [['Moğolistan'], 'Mongolia'],
  [['Moldova'], 'Moldova'],
  [['Moritanya'], 'Mauritania'],
  [['Mozambik'], 'Mozambique'],
  [['Myanmar'], 'Myanmar'],
  [['Namibya'], 'Namibia'],
  [['Nepal'], 'Nepal'],
  [['Nijer'], 'Niger'],
  [['Nijerya'], 'Nigeria'],
  [['Norveç'], 'Norway'],
  [['Özbekistan'], 'Uzbekistan'],
  [['Pakistan'], 'Pakistan'],
  [['Panama'], 'Panama'],
  [['Paraguay'], 'Paraguay'],
  [['Peru'], 'Peru'],
  [['Polonya'], 'Poland'],
  [['Portekiz'], 'Portugal'],
  [['Romanya'], 'Romania'],
  [['Ruanda'], 'Rwanda'],
  [['Rusya'], 'Russia'],
  [['Senegal'], 'Senegal'],
  [['Şili'], 'Chile'],
  [['Singapur'], 'Singapore'],
  [['Sırbistan'], 'Serbia'],
  [['Slovakya'], 'Slovakia'],
  [['Slovenya'], 'Slovenia'],
  [['Somali'], 'Somalia'],
  [['Sri Lanka'], 'Sri Lanka'],
  [['Sudan'], 'Sudan'],
  [['Suriye'], 'Syria'],
  [['Suudi Arabistan'], 'Saudi Arabia'],
  [['Tacikistan'], 'Tajikistan'],
  [['Tanzanya'], 'Tanzania'],
  [['Tayland'], 'Thailand'],
  [['Togo'], 'Togo'],
  [['Tunus'], 'Tunisia'],
  [['Türkmenistan'], 'Turkmenistan'],
  [['Uganda'], 'Uganda'],
  [['Ukrayna'], 'Ukraine'],
  [['Umman'], 'Oman'],
  [['Uruguay'], 'Uruguay'],
  [['Ürdün'], 'Jordan'],
  [['Vatikan'], null, [12.45, 41.9]],
  [['Venezuela'], 'Venezuela'],
  [['Vietnam'], 'Vietnam'],
  [['Yemen'], 'Yemen'],
  [['Yeni Zelanda'], 'New Zealand'],
  [['Yunanistan'], 'Greece'],
  [['Zambiya'], 'Zambia'],
  [['Zimbabve'], 'Zimbabwe'],
];

const lower = (s: string) => s.toLocaleLowerCase('tr');

// En uzun önek önce denenir ("Kongo Demokratik Cumhuriyeti" "Kongo"dan, "Güney Sudan" "Sudan"dan önce)
const PREFIXES = ENTRIES
  .flatMap(([prefixes, mapName, coord]) => prefixes.map(p => ({
    prefix: lower(p),
    country: { label: prefixes[0], mapName, coord } as MissionCountry,
  })))
  .sort((a, b) => b.prefix.length - a.prefix.length);

/** Misyon adından ülkeyi bulur; ad bir ülkeyle başlamıyorsa null */
export function countryOfMission(name: string): MissionCountry | null {
  const n = lower(name.trim());
  return PREFIXES.find(p => n === p.prefix || n.startsWith(p.prefix + ' '))?.country ?? null;
}
